// src/constants.js  —  Watersun Electrical Solutions Pvt Ltd
// Generated by SolarFlow Client Form · 6 August 2026 at 15:50
// CRN prefix: CRN-2026-

import {
    Users, ClipboardList, IndianRupee, Package, PauseCircle, Truck,
    Wrench, Camera, Send, Gauge, Zap, Activity, ClipboardCheck, CheckCircle2,
} from 'lucide-react';

export const PRIMARY_STAGES = [
    { id: 'LEADS', label: 'Leads', icon: Users },
    { id: 'REGISTRATION', label: 'Registration', icon: ClipboardList },
    { id: 'LOAN', label: 'Loan', icon: IndianRupee },
    { id: 'MATERIAL PROCUREMENT', label: 'Material Procurement', icon: Package },
    { id: 'HOLD PROCUREMENT', label: 'Hold Procurement', icon: PauseCircle },
    { id: 'MATERIAL DELIVERY', label: 'Material Delivery', icon: Truck },
    { id: 'INSTALLATION STATUS', label: 'Installation Status', icon: Wrench },
    { id: 'GEO TAG PHOTO', label: 'Geo Tag Photo', icon: Camera },
    { id: 'DISCOM SUBMISSION', label: 'Discom Submission', icon: Send },
    { id: 'METER INSTALLATION', label: 'Meter Installation', icon: Gauge },
    { id: 'SYSTEM COMMISSIONING', label: 'System Commissioning', icon: Zap },
    { id: 'METER PROCESS', label: 'Meter Process', icon: Activity },
    { id: 'DISCOM INSPECTION', label: 'Discom Inspection', icon: ClipboardCheck },
    { id: 'COMPLETED', label: 'Completed', icon: CheckCircle2 },
];



// Supabase metadata table categories (one per managed dropdown)
export const META_CATEGORIES = ['payment_type', 'module_brand', 'customer_type', 'payment_method_modes', 'subsidy_approval_status'];

export const USER_TYPE_OPTIONS = ['admin', 'sales', 'agent'];
export const ROLE_OPTIONS      = ['Manager', 'Sales Executive', 'Field Agent', 'Operations', 'Finance'];
