// src/models.jsx  —  Watersun Electrical Solutions Pvt Ltd
// Generated by SolarFlow Client Form · 6 August 2026 at 15:50
// Edit DEFAULT_PROJECT_CHECKLIST to match your actual workflow steps.

export const DEFAULT_PROJECT_CHECKLIST = [
    // ── Add your checklist steps here ─────────────────────────────────────────
    // Format: { id: 'unique_id', label: 'Step label', section: 'Section Name', checked: false }
    { id: 'step_1', label: 'Initial Registration Complete',  section: 'Registration', checked: false },
    { id: 'step_2', label: 'Documents Submitted',            section: 'Registration', checked: false },
    { id: 'step_3', label: 'Installation Done',              section: 'Installation', checked: false },
    { id: 'step_4', label: 'Meter Installed',                section: 'Post-Install', checked: false },
    { id: 'step_5', label: 'Subsidy Claimed',                section: 'Post-Install', checked: false },
    { id: 'step_6', label: 'Final Payment Cleared',          section: 'Post-Install', checked: false },
];

export function normalizeChecklist(rawChecklist) {
    let stored = [];
    if (Array.isArray(rawChecklist)) stored = rawChecklist;
    else if (typeof rawChecklist === 'string') {
        try { const p = JSON.parse(rawChecklist); if (Array.isArray(p)) stored = p; } catch {}
    }
    const byId = Object.fromEntries(stored.map(i => [i.id, i]));
    const merged = DEFAULT_PROJECT_CHECKLIST.map(i => ({
        ...i, ...byId[i.id],
        checked: byId[i.id]?.checked || false,
        checkedAt: byId[i.id]?.checkedAt || null,
        checkedBy: byId[i.id]?.checkedBy || null,
    }));
    const extra = stored.filter(i => !DEFAULT_PROJECT_CHECKLIST.some(d => d.id === i.id));
    return [...merged, ...extra];
}

export const DEFAULT_LEAD_FORM = {
    customer_name: '',
    phone_number: '',
    email_address: '',
    payment_type: '',
    villages: '',
    folder_no: '',
    system_capacity_kwp: '',
    module_brand: '',
    module_wp: '',
    registration_date: '',
    panel_serial_no: '',
    inverter_serial_no: '',
    invoice_no: '',
    loan_remarks: '',
    installation_status_remark: '',
    material_procurement_remark: '',
    customer_type: '',
    adhaar_card: false,
    adhaar_card_remarks: '',
    pan_card: false,
    pan_card_remarks: '',
    index_2: false,
    index_2_remarks: '',
    light_bill: false,
    light_bill_remarks: '',
    bank_details: false,
    bank_details_remarks: '',
    bank_passbook: false,
    bank_passbook_remarks: '',
    channel_partner: '',
    sub_channel_partner: '',
    consumer_no: '',
    sub_divisions: '',
    stage: 'LEADS',
};
